[package]
name = "cmap"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = "2.0"
proc-macro2 = "1.0"
quote = "1.0"
typenum = {version="1.18.0", features = ["const-generics"]}

[lib]
proc-macro = true
